# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c07c58594d07183c42f349dfb489beab3389a0af927e7851c2eca7d7b5c550c059ab331c1fae12b260e2b98121c369157bca57141fc9a74f64d02a174684977

test:
  secret_key_base: c7a039fcb6bc590b9d386049e41aa87d9cd65738952502462ae61b335291b2927d608d8f19b61870db3874c1f27e1e58933c88e86fd75b35ccc6dce1a5d8139c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
